// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreToolsTest.Models
{
    public partial class Logs
    {
        [Key]
        public int IdLog { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Description { get; set; }
    }
}