// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreToolsTest.Models
{
    [Keyless]
    public partial class REJEMPLO_PU
    {
        public int RecordId { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Student { get; set; }
        public int? Semester { get; set; }
        [Column(TypeName = "numeric(18, 2)")]
        public decimal? Qualification { get; set; }
    }
}