// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreToolsTest.Models
{
    [Index("Description", Name = "Uq_RolDescription", IsUnique = true)]
    public partial class Roles
    {
        public int AutoSec { get; set; }
        [Key]
        public Guid RoleId { get; set; }
        [StringLength(30)]
        [Unicode(false)]
        public string Description { get; set; }
    }
}