// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EfCoreToolsTest.Models
{
    public partial class UserRoleAssignment
    {
        public int AutoSec { get; set; }
        [Key]
        public Guid UserRoleAssignmentId { get; set; }
        public Guid UserId { get; set; }
        public Guid RolId { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("UserRoleAssignment")]
        public virtual Users User { get; set; }
    }
}